version: '3.10'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth

  auth:
    build: ./auth
    container_name: auth
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/videodb

  db:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_DB: videodb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
