services:
  redis:
    container_name: broker
    image: redis:alpine
    # healthcheck:
    #   test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    ports:
      - "6379:6379"
    # networks:
    #   - mi-red

  db:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U user"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # networks:
    #   - mi-red

# networks:
#   mi-red:
#     external: true

volumes:
  postgres_data: {}