services:
  worker:
    build: .
    networks:
      - mi-red
    environment:
      BROKER_URL: redis://10.128.0.13:6379/0
      DATABASE_URL: postgresql://postgres:postgres@10.128.0.13/postgres
      GOOGLE_APPLICATION_CREDENTIALS: gcp_key.json

networks:
  mi-red:
    external: true