services:
  web-server:
    image: adcastaneda2/web-server-api:api-v0.0.2
    build: .
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      SECRET_KEY: my-secret-key
      JWT_SECRET_KEY: my-jwt-secret-key
      DATABASE_URL: postgresql://postgres:postgres@35.188.46.139/postgres
      GOOGLE_APPLICATION_CREDENTIALS: gcp_key.json