services:
  web-server:
    build: .
    ports:
      - "80:5002"
    networks:
      - mi-red
    volumes:
      - /home/andersenpiano/shared-folder:/app/datos
    environment:
      SECRET_KEY: my-secret-key
      JWT_SECRET_KEY: my-jwt-secret-key
      DATABASE_URL: postgresql://postgres:postgres@10.128.0.30/postgres
      GOOGLE_APPLICATION_CREDENTIALS: gcp_key.json

networks:
  mi-red:
    external: true